### PR TITLE
That was an experience.

### PR DESCRIPTION
**Pull request by crodeheaver**
I had quite the experience rebasing this a few times. I think I got the process down now.

### CODE REVIEW

**Comment by barberboy** [comment]
Ha! Yeah, sorry about that. I guess that's life on the bleeding edge. Thanks for trying things out for me :)

**Comment by barberboy** [comment]
No doubt your gallery rendering ideas were much cooler than mine. You were probably already using ClojureScript and RxJS to render WebGL-based gallery animations. I look forward to seeing your version.

**Comment by barberboy** [comment]
I do have a couple things to note: .sort() sorts the array in place (does not make a copy) and returns the original array. Your code works and looks great, but I just wanted to make sure you knew the original array is sorted after running .sort().

Also, the rendering code assumes the key for the common name is `commonName` instead of `common_name` as you have it, though the tests don't check for it. If you take a look at http://crodeheaver.github.io/zookeep/, you'll see the effects of that in several places.

screen shot 2015-10-05 at 10 31 57 am

screen shot 2015-10-05 at 10 32 40 am

**Comment by crodeheaver** [comment]
@barberboy Is it me or does it seem like javascript functions are a bit arbitrary on when they create copies and send them back or does the work in place? Like sort vs concat. 

I've barely scratched clojurescript, but I want to redo the game-of-life-react in clojurescript and om! I went to a meetup last week and the guy gave a talk on clojure and suggested clojurescript because he was adamantly against javascript.

**Comment by barberboy** [comment]
Yes, I agree: seemingly arbitrary and very difficult to keep straight.

sort() makes some sense to me because the most memory-efficient sorting algorithms sort the array in place. Making an entirely new array every time you wanted it sorted would be inefficient. Same with reverse().

I often forget that concat() creates a **new** concatenated array. I think it is non-destructive to be consistent with String.concat(). If you do want a convenient destructive version, you can do `origArray.push.apply(origArray, moreValues)` (not that that's very intuitive).

The other mutators (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype#Mutator_methods) are relatively straightforward.

**Comment by barberboy** [comment]
Thanks for rebasing with the new tests! I really truly think I'm done tweaking now :)

:100:

**Comment by crodeheaver** [comment]
One last thing, when do you suggest using a rebase vs just pulling your changes?

**Comment by barberboy** [comment]
That's a good question for which I don't have a good answer ;)

The only time I use rebase is when I'm working on a fork, and there are changes on the upstream branch that I'd like to incorporate. I use rebase to bring in the upstream branch's changes, then (essentially) append my commits _after_ the upstream branch's (see https://github.com/unioncollege-webtech/sorts/pull/2#issuecomment-141308283). That makes for a cleaner, flatter commit history when my pull request gets merged into upstream.

That being said, I really don't understand rebase very well and don't use it often.

**Pull request closed without merging**
